### PR TITLE
New object model for CBL, CBL2 and FMP

### PR DESCRIPTION
**Pull request by jgomezr**

### CODE REVIEW

**Comment by lc0rp** [comment]
Can't merge...

**Comment by mugumedavid** [comment]
Hi Luke,

Just looked at the CI log emailed plus the pull-request. Looks like the
field _Submission__c_ is not defined on the objects

_From:_ Luke Kyohere [mailto:notifications@github.com]
_Sent:_ 6 March, 2015 19:06 PM
_To:_ grameenfoundation/applab-ug.salesforce
_Subject:_ Re: [applab-ug.salesforce] New object model for CBL, CBL2 and
FMP (#61)

Can't merge...

**Comment by lc0rp** [comment]
Great, thanks. Julian, possible to fix?

**Comment by jgomezr** [comment]
can't fix whit command line, Luke possibly you can do it because you are the manager of the repository

**Comment by mugumedavid** [comment]
Am still trying to delete the problematic commits. This should fix the
issue.

Moving forward, I am researching on a github API where I could be able to
revert a merged pull-request that fails

_From:_ Luke Kyohere [mailto:notifications@github.com]
_Sent:_ 7 March, 2015 5:40 AM
_To:_ grameenfoundation/applab-ug.salesforce
_Cc:_ David Mugume
_Subject:_ Re: [applab-ug.salesforce] New object model for CBL, CBL2 and
FMP (#61)

Great, thanks. Julian, possible to fix?

**Pull request closed without merging**
